# Generated by Django 5.1.5 on 2025-01-20 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmodel',
            old_name='sender',
            new_name='username',
        ),
    ]
